#!/bin/bash

# Atualizar repositórios e aplicativos
sudo apt update && sudo apt upgrade

# Instalar dependências
sudo apt install curl git apache2 mysql php php-mysql php-mbstring php-xml php-curl php-common php-json php-cli --yes

## Instalação do Node e do NPM
# Obtendo a versão do Node mais recente
NODE_VERSION=$(curl 'https://nodejs.org/download/release/index.tab' --silent | awk 'NR==2 {print $1}')
FILE_NAME="node-${NODE_VERSION}-linux-x64"

# Baixando e extraindo o Node
wget "https://nodejs.org/dist/latest/${FILE_NAME}.tar.gz"
tar xvf "${FILE_NAME}.tar.gz"
cd "${FILE_NAME}/bin"

# Instalando Node e NPM
sudo mv node /usr/bin/
sudo ./npm i -g npm

# Excluindo arquivos de instalação
cd ../../
sudo rm -rf "${FILE_NAME}"
sudo rm "${FILE_NAME}.tar.gz"

## Instalação do composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
sudo mv composer.phar /usr/local/bin/composer
