#!/bin/bash

# Clonando o repositório
git clone git@github.com:forsoft-2013/ProjetoSUS.git ProjetoSUS

cd ProjetoSUS

# Instalando dependências do PHP
composer install

# Permissão em storage e bootstrap/cache
sudo chmod 777 -R storage bootstrap/cache

# Instalando dependências do JavaScript
npm i

# Criando arquivo de configuração
cp .env.example .env

# Gerando chave de aplicação
php artisan key:generate

# Abrindo o arquivo .env para ser configurado
nano .env

echo -e "\n\nProjeto configurado com sucesso!"
echo -e "\nPara testar rode os seguintes comandos:"
echo -e "\n> cd ProjetoSUS"
echo -e "\n> php artisan serve"
echo -e "\n\nAcesse pelo Endereço: http://localhost:8000"
